// Aporte nutricional por unidad/porción. Valores estimados a modo de referencia inicial — verificar y ajustar.
export const alimentosFiestasPatrias = [
    {
        id: 'choripan',
        nombre: 'Choripán',
        porcion: '1 unidad (pan + chorizo, ~180g)',
        calorias: 480,
        proteina: 20,
        carbohidrato: 38,
        lipidos: 28,
    },
    {
        id: 'mayonesa',
        nombre: 'Mayonesa',
        porcion: '1 porción (2 cucharadas, ~30g)',
        calorias: 205,
        proteina: 0.3,
        carbohidrato: 0.6,
        lipidos: 22,
    },
    {
        id: 'pebre',
        nombre: 'Pebre',
        porcion: '1 porción (2 cucharadas, ~30g)',
        calorias: 35,
        proteina: 0.5,
        carbohidrato: 3,
        lipidos: 2.5,
    },
    {
        id: 'ketchup',
        nombre: 'Ketchup',
        porcion: '1 porción (1 cucharada, ~15g)',
        calorias: 15,
        proteina: 0.2,
        carbohidrato: 4,
        lipidos: 0,
    },
    {
        id: 'empanada-pino',
        nombre: 'Empanada de pino chilena',
        porcion: '1 unidad (~180g)',
        calorias: 450,
        proteina: 15,
        carbohidrato: 40,
        lipidos: 25,
    },
    {
        id: 'terremoto',
        nombre: 'Terremoto',
        porcion: '1 vaso (350ml)',
        calorias: 300,
        proteina: 1,
        carbohidrato: 45,
        lipidos: 3,
    },
    {
        id: 'chicha',
        nombre: 'Chicha chilena',
        porcion: '1 vaso (350ml)',
        calorias: 150,
        proteina: 0.3,
        carbohidrato: 20,
        lipidos: 0,
    },
];
